# Generated by Django 2.2.2 on 2019-06-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField(verbose_name='')),
                ('longitude', models.FloatField(verbose_name='')),
                ('height', models.FloatField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Tasbir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasbir', models.ImageField(upload_to='bin_images')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Locality')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='')),
                ('date', models.DateTimeField(verbose_name='')),
                ('verification', models.BooleanField(verbose_name='')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Locality')),
            ],
        ),
    ]
