# Generated by Django 2.2.2 on 2019-06-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='height',
            field=models.CharField(max_length=200),
        ),
    ]
